(* ::Package:: *)

(* Autogenerated Package *)

PrettyString::usage=
	"Makes a pretty string form for an expression";
PrettyExport::usage=
	"Exports an expression in prettier form";


Begin["`Private`"];


PublicPacletServer; (* invoke the autoloader *)


(* ::Subsubsection::Closed:: *)
(*PrettyString*)



PrettyString[
	expr_,
	elementsPerLine:_?IntegerQ:1,
	dataType:TextData|BoxData:BoxData,
	cellStyle_String:"Input",
	ops:OptionsPattern[Cell]
	]:=
	StringDelete[
		FrontEndExecute[
			FrontEnd`ExportPacket[
				Cell[
					dataType@
						GeneralUtilities`PrettyFormBoxes[expr, 1]/.
							TemplateBox[
								{sym_, ___},
								"DefinitionSymbol", 
								___
								]:>sym, 
					cellStyle,
					ops,
					PageWidth->Infinity
					], 
				"PlainText"
				]
			][[1]],
		"\\"~~"\n"
		]


(* ::Subsubsection::Closed:: *)
(*PrettyExport*)



PrettyExport[
	file_,
	expr_,
	args___
	]:=
	With[{tt=PrettyString[expr, args]},
		If[StringQ@tt, Export[file, tt, "Text"], $Failed]
		];


End[];



